### ISSUE TITLE
Econometrics in Python part III: `dfSetI` variable.

### ISSUE THREAD

**Issue by egglang** [aeturrell/home#1]
Hi, 

Thanks for your publishing very useful articles.
https://github.com/aeturrell/home/commit/79a3972294ac4bb3c878c32e46a15466be4878ff#diff-880d4c43fbb40df749ef37cac50da26bR132
I guess the  `dfSetI` is probably a data frame of pandas, but I'm not sure how to create it from `setI` or something.
Would you please add some explanation to create the  `dfSetI` on the post?

**Comment by aeturrell** [comment]
Hi,

Thanks for your email. It's always nice to know that posts are being read,
and even better that they are useful.

There was a missing line from the code which I include below. I have also
updated the post.

# Draw a random subsample of size s.# Choose s ints between 0 and n
randomlysubSampleMask = random.sample(range(0, n), s)# Create set
IsetIMask = random.sample(subSampleMask, np.int(np.ceil(s/2.)))setI =
[X[setIMask]]dfSetI = pd.DataFrame(data=X[setIMask])# Create set
JsetJMask = [i for i in subSampleMask if i not in setIMask]setJ =
[X[setJMask]]


Hope this sorts it. Good luck with looking at heterogeneous treatment
effects!

Regards,
Arthur

**Comment by egglang** [comment]
Hi, Arthur.

Thank you for your prompt reply.
Finally, it worked fine without any problem!

I appreciate your time and explanations very much. Thanks again.
